### PR TITLE
LDAP User Authentication, Roles, & Archived Projects

### PR DESCRIPTION
**Pull request by bradly**
Hey guys,

I did some work for a large agency that needed LDAP authentication, roles, and archiving of projects. Do you think these are features that you would like in the main repo? The pull request is for all of the features, but I can separate them out individually if you think only 1 or 2 are beneficial to the project.

Thanks!
Bradly

### CODE REVIEW

**Comment by j15e** [comment]
It would be nice to make LDAP optional as it add dependencies

It requires the net-ldap gem which requires Ruby version >= 1.8.7

I have pull this in my repo for the roles, but I manually disabled the LDAP part because I can't update to 1.8.7

(thanks for the roles feature!)

PS. I would add restrictions for non-admin users to view other users profiles and non-assigned projects deployments logs

**Comment by sroze** [comment]
Roles could be really interesting! I would like this feature to be merged!
Thanks a lot for your work.

**Comment by dlsniper** [comment]
@peritor guys is this still maintented? And if so, this would be interesting if it could be merged. Thanks

**Comment by Kumar82** [comment]
I getting the Error when configuring LDAP plugin with webistrano as given below.. Could any one help on this..

You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.first

**Comment by eXistenZNL** [comment]
Peritor abandoned this project long ago.

**Pull request closed without merging**
